// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import EmptyStateController from "./empty_state_controller.js"
application.register("empty-state", EmptyStateController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MasonryController from "./masonry_controller.js"
application.register("masonry", MasonryController)
