// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import EmptyStateController from "./empty_state_controller.js"
application.register("empty-state", EmptyStateController)

import FileUploadController from "./file_upload_controller.js"
application.register("file-upload", FileUploadController)

import FormController from "./form_controller.js"
application.register("form", FormController)

import FrameController from "./frame_controller.js"
application.register("frame", FrameController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MasonryController from "./masonry_controller.js"
application.register("masonry", MasonryController)

import ProgressController from "./progress_controller.js"
application.register("progress", ProgressController)

import VideoPreviewController from "./video_preview_controller.js"
application.register("video-preview", VideoPreviewController)
