# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class OrderMailer
  sig { returns(ActionMailer::MessageDelivery) }
  def self.confirmation_email; end
end
