# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_28; end
module ::Anonymous_Delegator_8; end
module ::Spring; end
module ActionDispatch::Response::ContentTypeHeader; end
module Rails::Engine::Configuration; end
module T::Private::Methods::MethodHooks; end
module T::Private::Methods::SingletonMethodHooks; end
